[package]
name = "nu_plugin_clipboard"
license = "MIT"
authors = ["Motalleb Fallahnezhad <fmotalleb@gmail.com>"]
keywords = ["nushell", "clipboard", "plugin"]
homepage = "https://github.com/FMotalleb/nu_plugin_clipboard"
repository = "https://github.com/FMotalleb/nu_plugin_clipboard"
description = "A nushell plugin to copy text into clipboard or get text from it."
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
nu-plugin = "0.87.0"
nu-protocol = { version = "0.87.0", features = ["plugin"] }
arboard = { version = "3.2.1" }
cli-clipboard = "0.4.0"

[features]
default = ["force-x11"]
force-x11 = []
use-wayland = ["arboard/wayland-data-control"]
